#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d K U 2 N   
$HOME/.config/polybar/launch.sh
$HOME/.config/sxhkd/scripts/cleanfullscreen

bspc config border_width         	3
bspc config focused_border_color	"#8FBCBB"
bspc config window_gap		 	6

bspc config split_ratio          	0.52
bspc config focus_follows_pointer	true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config pointer_modifier		mod1

# move window with mouse
bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
